### ISSUE TITLE
amdgpu.ids: No such file or directory

### ISSUE THREAD

**Issue by Gloster10** [svt/vivictpp#16] opened 2022-06-05 05:10 UTC
Use : Ubuntu 20.04, installed vivivtpp via "ubuntu Software" (snap), Window manager X11
I use the following command : 
vivictpp "Die Geistervilla.mp4" "Die Geistervilla 22.mp4"
The first file : h.262, the second h.265.
Framerate, resolution, codec will be recognized correctly, but no video output. After approximately 15sec also no audio output anymore.

After program start I get the message : "/usr/share/libdrm/amdgpu.ids: No such file or directory"

The file is present, has someone an idea how  to solve this problem ?

ps.: A good idea this tool !

**Comment by grusell** [comment] 2022-06-07 04:47
As far as I can tell, it seems that the AMD drivers sometimes don't work correctly with snaps. Unfortunately I am unable to investigate this since I don't have access to an AMD-graphics card.

Could you try to compile and install from source according to the instructions in the README ?

**Comment by Gloster10** [comment] 2022-06-07 14:33
Try to compile, the complete command list what I did :
`sudo apt-get --fix-missing install -y cmake python3-pip gcc python3-setuptools   python3-wheel libsdl2-dev libsdl2-ttf-dev libfreetype6-dev libavformat-dev libavcodec-dev  libavfilter-dev libswscale-dev pkg-config` 
(added libavfilter-dev)
`git clone https://github.com/svt/vivictpp` 
`cd vivictpp`
I have an older version of cmake (Ubuntu 20.04), therefore upgraded as described here :
https://askubuntu.com/questions/355565/how-do-i-install-the-latest-version-of-cmake-from-the-command-line
`meson setup builddir`
`meson compile -C builddir`
`cd builddir`
copy films to builddir and called the program :
`./vivictpp "Die Geistervilla.mp4" "Die Geistervilla 22.mp4"`

Now, I get no error message anymore, but the video will not be seen as before.

Is it possible to get some debug outputs written in a log-file via added calling parameter.
Or further more, if not, if you would add some debug outputs in code, i would compile it again, and would send you the debug information.

**Comment by grusell** [comment] 2022-06-07 15:15
You can get debug output by setting the `SPDLOG_LEVEL` environment variable like described [here](https://github.com/svt/vivictpp#loggingl). Logging will be done to stdout, but you could use `tee` to write it to a file. If it's is not obvious from the log what the problem is you could attach the log file here and I will take a look.
```SPDLOG_LEVE=DEBUG ./vivictpp "Die Geistervilla.mp4" "Die Geistervilla 22.mp4" | tee log.txt```

**Comment by Gloster10** [comment] 2022-06-07 16:41
Both possible traces I did, please refer to attachment :
[DebugLog.txt.gz](https://github.com/svt/vivictpp/files/8855015/DebugLog.txt.gz)
[Tracelog.txt.gz](https://github.com/svt/vivictpp/files/8855016/Tracelog.txt.gz)

I did wait until audio switched off by the program.

**Comment by grusell** [comment] 2022-06-09 06:30
I only had time to take a quick look in the look but I wasn't able to spot the cause of the problem.

Audiosync sometimes causes problem, so it might be worth testing playback without audio by using the `--disable-audio` flag.

Also if it would be possible to share any of the files that causes trouble that would make investigation easier.

**Comment by Gloster10** [comment] 2022-06-09 12:43
Please use this link to get some files for test purpose :
https://we.tl/t-hZRM5ErwI3
The link will be 1 week alive
Thank you for investigation.

**Comment by grusell** [comment] 2022-06-09 15:20
Ok I had a look and there seems to be a few different problems here.
1. Audio causes problems, maybe because of 5.1 audio in some of the files or it has something todo with the timestamps in audio streams. I would recommend running vivictpp with `--disable-audio` .
2. When opening two videos at the same time, apparently vivictpp doesn't handle very well if the videos have different start timestamps which seems to be the case here. A workaround is to use the 'Frame offset' feature to offset the timetamps of one video. For instance, if you want to wach two videos where one starts at 0 and the other one at 0.120, setting a frame offset of 3 (or -3 depending on which video is left or right), should enable vivictpp to play them both. Given a frame duration of 40ms, ie 25fps.

I will investigate these problems some more but I hope the above workarounds will help you in the meantime.

**Comment by Gloster10** [comment] 2022-06-16 20:43
Unfortunately, to increase/decrease start time stamp of the first film does not work on my system. But I have found a way to use your tool as I need (check compressed ts-files with different crf).
1. Convert the original file to mp4-container, also the compressed file (as test only the first 5 minutes will be compressed, ffmpeg stopped with one time ctrl-c, will generate a playable file)
2. Set the start time stamp of  both films to 0, e.g.: 
`ffmpeg -i "The Others_h265.mp4" -map 0 -c copy -muxpreload 0 -muxdelay 0 "The Others_h265_0.mp4"`
(with ts-files, I got every time an offset) 
3. And after all I can compare the quality of both films with your tool. 
It is not necessary to cut the original film, the tool will compare both films with totally different length, and stops at the end of the shorter film.
Grusell, well done !

**Comment by grusell** [comment] 2022-06-17 05:55
Great that you found a workaround! For the record, I am also working on a fix to allow vivictpp to handle files with different starting timestamps cleanly.

**Comment by Gloster10** [comment] 2022-06-17 06:29
A minor correction of the above.
It is possible to change the container (s. 1) and to set the start time stamp to 0 (s. 2) via a single command :

`ffmpeg -i "The Others_h265.ts" -map 0 -c copy -muxpreload 0 -muxdelay 0 "The Others_h265_0.mp4"`

**Comment by grusell** [comment] 2022-08-05 13:47
Sounds like a decent workaround, will close this issue.

**Closed by grusell** 2022-08-05 13:47 UTC
Labels: bug
